#build stage
FROM nilorg/golang:latest AS builder
WORKDIR /src
COPY . .
RUN go build -mod=vendor -o ./bin/token-server -i ./cmd/token-server/main.go

#final stage
FROM nilorg/alpine:latest
WORKDIR /workspace
COPY --from=builder /src/bin/token-server .
ENTRYPOINT ./token-server
EXPOSE 8081