apiVersion: apps/v1
kind: Deployment
metadata:
  name: naas
  namespace: nilorg
spec:
  selector:
    matchLabels:
      app: naas
      service: naas
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: naas
        service: naas
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: naas
          image: nilorg/naas:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 5000
            - containerPort: 9000
          env:
            - name: GRPC_ENABLE
              value: "true"
            - name: GRPC_GATEWAY_ENABLE
              value: "true"
            - name: HTTP_ENABLE
              value: "true"
          volumeMounts:
            - name: config-cm
              mountPath: /workspace/configs/
      volumes:
        - name: config-cm
          configMap:
            name: naas