// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/account.proto

package proto // import "github.com/nilorg/naas/pkg/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import errors "github.com/nilorg/protobuf/errors"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserDetail struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_017431f86e895a38, []int{0}
}
func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (dst *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(dst, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserDetail) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserDetail) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *UserDetail) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *UserDetail) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetCurrentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentRequest) Reset()         { *m = GetCurrentRequest{} }
func (m *GetCurrentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentRequest) ProtoMessage()    {}
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_017431f86e895a38, []int{1}
}
func (m *GetCurrentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentRequest.Unmarshal(m, b)
}
func (m *GetCurrentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentRequest.Marshal(b, m, deterministic)
}
func (dst *GetCurrentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentRequest.Merge(dst, src)
}
func (m *GetCurrentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentRequest.Size(m)
}
func (m *GetCurrentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentRequest proto.InternalMessageInfo

type GetCurrentResponse struct {
	Err                  *errors.BusinessError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	UserDetail           *UserDetail           `protobuf:"bytes,2,opt,name=userDetail,proto3" json:"userDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetCurrentResponse) Reset()         { *m = GetCurrentResponse{} }
func (m *GetCurrentResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentResponse) ProtoMessage()    {}
func (*GetCurrentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_017431f86e895a38, []int{2}
}
func (m *GetCurrentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentResponse.Unmarshal(m, b)
}
func (m *GetCurrentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentResponse.Marshal(b, m, deterministic)
}
func (dst *GetCurrentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentResponse.Merge(dst, src)
}
func (m *GetCurrentResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentResponse.Size(m)
}
func (m *GetCurrentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentResponse proto.InternalMessageInfo

func (m *GetCurrentResponse) GetErr() *errors.BusinessError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetCurrentResponse) GetUserDetail() *UserDetail {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDetail)(nil), "nilorg.naas.pkg.proto.UserDetail")
	proto.RegisterType((*GetCurrentRequest)(nil), "nilorg.naas.pkg.proto.GetCurrentRequest")
	proto.RegisterType((*GetCurrentResponse)(nil), "nilorg.naas.pkg.proto.GetCurrentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error) {
	out := new(GetCurrentResponse)
	err := c.cc.Invoke(ctx, "/nilorg.naas.pkg.proto.Account/GetCurrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	GetCurrent(context.Context, *GetCurrentRequest) (*GetCurrentResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilorg.naas.pkg.proto.Account/GetCurrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetCurrent(ctx, req.(*GetCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nilorg.naas.pkg.proto.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrent",
			Handler:    _Account_GetCurrent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/account.proto",
}

func init() { proto.RegisterFile("pkg/proto/account.proto", fileDescriptor_account_017431f86e895a38) }

var fileDescriptor_account_017431f86e895a38 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xe4, 0x40,
	0x10, 0xc7, 0x49, 0x66, 0xbf, 0xa6, 0x06, 0x96, 0xdd, 0x5e, 0x96, 0x0d, 0xc3, 0x2e, 0xcc, 0x06,
	0x84, 0x11, 0xa1, 0x1b, 0xc6, 0x83, 0xe7, 0x8c, 0x8a, 0xf7, 0x80, 0x17, 0x2f, 0x43, 0x27, 0x29,
	0x63, 0x33, 0x99, 0xee, 0xd8, 0x1f, 0x27, 0x6f, 0x1e, 0x3c, 0x0b, 0xe2, 0x93, 0xf9, 0x0a, 0x3e,
	0x88, 0x24, 0xdd, 0xf3, 0x01, 0x2a, 0x78, 0x0a, 0xf5, 0xff, 0x57, 0x55, 0xea, 0x57, 0x5d, 0xf0,
	0xa7, 0x5d, 0xd6, 0xac, 0xd5, 0xca, 0x2a, 0xc6, 0xcb, 0x52, 0x39, 0x69, 0x69, 0x1f, 0x91, 0xdf,
	0x52, 0x34, 0x4a, 0xd7, 0x54, 0x72, 0x6e, 0x68, 0xbb, 0xac, 0xbd, 0x3c, 0xfe, 0x5b, 0x2b, 0x55,
	0x37, 0xc8, 0x78, 0x2b, 0x18, 0x97, 0x52, 0x59, 0x6e, 0x85, 0x92, 0x26, 0xb8, 0x07, 0xbe, 0xc8,
	0x37, 0x2c, 0xdc, 0x25, 0x43, 0xad, 0x95, 0x36, 0xac, 0x70, 0x46, 0x48, 0x34, 0x66, 0xd1, 0xc7,
	0x3e, 0x39, 0x7d, 0x8c, 0x00, 0xce, 0x0d, 0xea, 0x13, 0xb4, 0x5c, 0x34, 0xe4, 0x3b, 0xc4, 0xa2,
	0x4a, 0xa2, 0x49, 0x34, 0x1d, 0xe6, 0xb1, 0xa8, 0xc8, 0x3f, 0x80, 0x52, 0x23, 0xb7, 0x58, 0x2d,
	0xb8, 0x4d, 0xe2, 0x49, 0x34, 0x1d, 0xe4, 0xc3, 0xa0, 0x64, 0xb6, 0xb3, 0x5d, 0x5b, 0xad, 0xed,
	0x81, 0xb7, 0x83, 0xe2, 0xed, 0x0a, 0x1b, 0x0c, 0xf6, 0x27, 0x6f, 0x07, 0x25, 0xb3, 0x64, 0x0c,
	0xdf, 0x9c, 0x41, 0x2d, 0xf9, 0x0a, 0x93, 0xcf, 0xfd, 0x2f, 0x37, 0x71, 0xfa, 0x0b, 0x7e, 0x9e,
	0xa1, 0x3d, 0x76, 0x5a, 0xa3, 0xb4, 0x39, 0x5e, 0x3b, 0x34, 0x36, 0xbd, 0x8f, 0x80, 0xec, 0xaa,
	0xa6, 0x55, 0xd2, 0x20, 0x39, 0x82, 0x01, 0x6a, 0xdd, 0x4f, 0x3d, 0x9a, 0xed, 0xd1, 0xb0, 0xb3,
	0x35, 0x3e, 0xf5, 0xf8, 0x74, 0x1e, 0xf0, 0x4f, 0xbb, 0x30, 0xef, 0x2a, 0x48, 0x06, 0xe0, 0x36,
	0xec, 0x3d, 0xdd, 0x68, 0xf6, 0x9f, 0xbe, 0xb9, 0x73, 0xba, 0x5d, 0x52, 0xbe, 0x53, 0x34, 0xbb,
	0x8b, 0xe0, 0x6b, 0xe6, 0xdf, 0x8c, 0xdc, 0x00, 0x6c, 0xa7, 0x23, 0xd3, 0x77, 0x1a, 0xbd, 0xc2,
	0x1a, 0xef, 0x7f, 0x20, 0xd3, 0xa3, 0xa6, 0xc9, 0xed, 0xd3, 0xf3, 0x43, 0x4c, 0xc8, 0x8f, 0xf5,
	0xa1, 0xb0, 0xd2, 0x67, 0xcc, 0xd3, 0x8b, 0x49, 0x2d, 0xec, 0x95, 0x2b, 0x68, 0xa9, 0x56, 0x2c,
	0x9c, 0x40, 0xd7, 0x90, 0x6d, 0x8e, 0xab, 0xf8, 0xd2, 0x7f, 0x0e, 0x5f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x70, 0x63, 0x1a, 0x87, 0x70, 0x02, 0x00, 0x00,
}
