// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.4
// source: pkg/proto/casbin-adapter.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// LoadPolicyRequest 加载策略请求
type LoadPolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId     string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceSecret string `protobuf:"bytes,2,opt,name=resource_secret,json=resourceSecret,proto3" json:"resource_secret,omitempty"`
}

func (x *LoadPolicyRequest) Reset() {
	*x = LoadPolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_casbin_adapter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPolicyRequest) ProtoMessage() {}

func (x *LoadPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_casbin_adapter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPolicyRequest.ProtoReflect.Descriptor instead.
func (*LoadPolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_casbin_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *LoadPolicyRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LoadPolicyRequest) GetResourceSecret() string {
	if x != nil {
		return x.ResourceSecret
	}
	return ""
}

// LoadPolicyResponse 加载策略响应
type LoadPolicyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policys []string `protobuf:"bytes,1,rep,name=policys,proto3" json:"policys,omitempty"`
}

func (x *LoadPolicyResponse) Reset() {
	*x = LoadPolicyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_casbin_adapter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPolicyResponse) ProtoMessage() {}

func (x *LoadPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_casbin_adapter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPolicyResponse.ProtoReflect.Descriptor instead.
func (*LoadPolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_casbin_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *LoadPolicyResponse) GetPolicys() []string {
	if x != nil {
		return x.Policys
	}
	return nil
}

var File_pkg_proto_casbin_adapter_proto protoreflect.FileDescriptor

var file_pkg_proto_casbin_adapter_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x73, 0x62,
	0x69, 0x6e, 0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x6e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x6e, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x6b,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x73, 0x32, 0x98, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x41,
	0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x86, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x64, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x28, 0x2e, 0x6e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x6e,
	0x61, 0x61, 0x73, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x6e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x6e, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x6b,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x63, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x2d, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42,
	0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69,
	0x6c, 0x6f, 0x72, 0x67, 0x2f, 0x6e, 0x61, 0x61, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_casbin_adapter_proto_rawDescOnce sync.Once
	file_pkg_proto_casbin_adapter_proto_rawDescData = file_pkg_proto_casbin_adapter_proto_rawDesc
)

func file_pkg_proto_casbin_adapter_proto_rawDescGZIP() []byte {
	file_pkg_proto_casbin_adapter_proto_rawDescOnce.Do(func() {
		file_pkg_proto_casbin_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_casbin_adapter_proto_rawDescData)
	})
	return file_pkg_proto_casbin_adapter_proto_rawDescData
}

var file_pkg_proto_casbin_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_casbin_adapter_proto_goTypes = []interface{}{
	(*LoadPolicyRequest)(nil),  // 0: nilorg.naas.pkg.proto.LoadPolicyRequest
	(*LoadPolicyResponse)(nil), // 1: nilorg.naas.pkg.proto.LoadPolicyResponse
}
var file_pkg_proto_casbin_adapter_proto_depIdxs = []int32{
	0, // 0: nilorg.naas.pkg.proto.CasbinAdapter.LoadPolicy:input_type -> nilorg.naas.pkg.proto.LoadPolicyRequest
	1, // 1: nilorg.naas.pkg.proto.CasbinAdapter.LoadPolicy:output_type -> nilorg.naas.pkg.proto.LoadPolicyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_casbin_adapter_proto_init() }
func file_pkg_proto_casbin_adapter_proto_init() {
	if File_pkg_proto_casbin_adapter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_casbin_adapter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadPolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_casbin_adapter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadPolicyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_casbin_adapter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_casbin_adapter_proto_goTypes,
		DependencyIndexes: file_pkg_proto_casbin_adapter_proto_depIdxs,
		MessageInfos:      file_pkg_proto_casbin_adapter_proto_msgTypes,
	}.Build()
	File_pkg_proto_casbin_adapter_proto = out.File
	file_pkg_proto_casbin_adapter_proto_rawDesc = nil
	file_pkg_proto_casbin_adapter_proto_goTypes = nil
	file_pkg_proto_casbin_adapter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CasbinAdapterClient is the client API for CasbinAdapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CasbinAdapterClient interface {
	// LoadPolicy 加载策略
	LoadPolicy(ctx context.Context, in *LoadPolicyRequest, opts ...grpc.CallOption) (*LoadPolicyResponse, error)
}

type casbinAdapterClient struct {
	cc grpc.ClientConnInterface
}

func NewCasbinAdapterClient(cc grpc.ClientConnInterface) CasbinAdapterClient {
	return &casbinAdapterClient{cc}
}

func (c *casbinAdapterClient) LoadPolicy(ctx context.Context, in *LoadPolicyRequest, opts ...grpc.CallOption) (*LoadPolicyResponse, error) {
	out := new(LoadPolicyResponse)
	err := c.cc.Invoke(ctx, "/nilorg.naas.pkg.proto.CasbinAdapter/LoadPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasbinAdapterServer is the server API for CasbinAdapter service.
type CasbinAdapterServer interface {
	// LoadPolicy 加载策略
	LoadPolicy(context.Context, *LoadPolicyRequest) (*LoadPolicyResponse, error)
}

// UnimplementedCasbinAdapterServer can be embedded to have forward compatible implementations.
type UnimplementedCasbinAdapterServer struct {
}

func (*UnimplementedCasbinAdapterServer) LoadPolicy(context.Context, *LoadPolicyRequest) (*LoadPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadPolicy not implemented")
}

func RegisterCasbinAdapterServer(s *grpc.Server, srv CasbinAdapterServer) {
	s.RegisterService(&_CasbinAdapter_serviceDesc, srv)
}

func _CasbinAdapter_LoadPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinAdapterServer).LoadPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilorg.naas.pkg.proto.CasbinAdapter/LoadPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinAdapterServer).LoadPolicy(ctx, req.(*LoadPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CasbinAdapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nilorg.naas.pkg.proto.CasbinAdapter",
	HandlerType: (*CasbinAdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadPolicy",
			Handler:    _CasbinAdapter_LoadPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/casbin-adapter.proto",
}
