// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/permission.proto

package proto // import "github.com/nilorg/naas/pkg/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import errors "github.com/nilorg/protobuf/errors"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// VerificationHttpRouterRequest 验证HTTP路由权限请求参数
type VerificationHttpRouterRequest struct {
	// token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 客户端ID
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 路由
	Router string `protobuf:"bytes,3,opt,name=router,proto3" json:"router,omitempty"`
	// 请求方法
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// 是否返回用户信息,token验证通过的情况下
	ReturnUserInfo       bool     `protobuf:"varint,5,opt,name=return_user_info,json=returnUserInfo,proto3" json:"return_user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationHttpRouterRequest) Reset()         { *m = VerificationHttpRouterRequest{} }
func (m *VerificationHttpRouterRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationHttpRouterRequest) ProtoMessage()    {}
func (*VerificationHttpRouterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{0}
}
func (m *VerificationHttpRouterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationHttpRouterRequest.Unmarshal(m, b)
}
func (m *VerificationHttpRouterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationHttpRouterRequest.Marshal(b, m, deterministic)
}
func (dst *VerificationHttpRouterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationHttpRouterRequest.Merge(dst, src)
}
func (m *VerificationHttpRouterRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationHttpRouterRequest.Size(m)
}
func (m *VerificationHttpRouterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationHttpRouterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationHttpRouterRequest proto.InternalMessageInfo

func (m *VerificationHttpRouterRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerificationHttpRouterRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VerificationHttpRouterRequest) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *VerificationHttpRouterRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *VerificationHttpRouterRequest) GetReturnUserInfo() bool {
	if m != nil {
		return m.ReturnUserInfo
	}
	return false
}

// VerificationHttpRouterResponse 验证HTTP路由权限响应参数
type VerificationHttpRouterResponse struct {
	Err *errors.BusinessError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	// 是否允许
	Allow bool `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	// 用户信息
	UserInfo             *VerificationHttpRouterResponse_UserInfo `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *VerificationHttpRouterResponse) Reset()         { *m = VerificationHttpRouterResponse{} }
func (m *VerificationHttpRouterResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationHttpRouterResponse) ProtoMessage()    {}
func (*VerificationHttpRouterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{1}
}
func (m *VerificationHttpRouterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationHttpRouterResponse.Unmarshal(m, b)
}
func (m *VerificationHttpRouterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationHttpRouterResponse.Marshal(b, m, deterministic)
}
func (dst *VerificationHttpRouterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationHttpRouterResponse.Merge(dst, src)
}
func (m *VerificationHttpRouterResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationHttpRouterResponse.Size(m)
}
func (m *VerificationHttpRouterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationHttpRouterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationHttpRouterResponse proto.InternalMessageInfo

func (m *VerificationHttpRouterResponse) GetErr() *errors.BusinessError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *VerificationHttpRouterResponse) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

func (m *VerificationHttpRouterResponse) GetUserInfo() *VerificationHttpRouterResponse_UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// 用户信息
type VerificationHttpRouterResponse_UserInfo struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Gender               uint32   `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationHttpRouterResponse_UserInfo) Reset() {
	*m = VerificationHttpRouterResponse_UserInfo{}
}
func (m *VerificationHttpRouterResponse_UserInfo) String() string { return proto.CompactTextString(m) }
func (*VerificationHttpRouterResponse_UserInfo) ProtoMessage()    {}
func (*VerificationHttpRouterResponse_UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{1, 0}
}
func (m *VerificationHttpRouterResponse_UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationHttpRouterResponse_UserInfo.Unmarshal(m, b)
}
func (m *VerificationHttpRouterResponse_UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationHttpRouterResponse_UserInfo.Marshal(b, m, deterministic)
}
func (dst *VerificationHttpRouterResponse_UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationHttpRouterResponse_UserInfo.Merge(dst, src)
}
func (m *VerificationHttpRouterResponse_UserInfo) XXX_Size() int {
	return xxx_messageInfo_VerificationHttpRouterResponse_UserInfo.Size(m)
}
func (m *VerificationHttpRouterResponse_UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationHttpRouterResponse_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationHttpRouterResponse_UserInfo proto.InternalMessageInfo

func (m *VerificationHttpRouterResponse_UserInfo) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *VerificationHttpRouterResponse_UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerificationHttpRouterResponse_UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *VerificationHttpRouterResponse_UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *VerificationHttpRouterResponse_UserInfo) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

// VerificationTokenRequest 验证Token请求参数
type VerificationTokenRequest struct {
	// token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 客户端ID
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 是否返回用户信息,token验证通过的情况下
	ReturnUserInfo       bool     `protobuf:"varint,5,opt,name=return_user_info,json=returnUserInfo,proto3" json:"return_user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationTokenRequest) Reset()         { *m = VerificationTokenRequest{} }
func (m *VerificationTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationTokenRequest) ProtoMessage()    {}
func (*VerificationTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{2}
}
func (m *VerificationTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationTokenRequest.Unmarshal(m, b)
}
func (m *VerificationTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationTokenRequest.Marshal(b, m, deterministic)
}
func (dst *VerificationTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationTokenRequest.Merge(dst, src)
}
func (m *VerificationTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationTokenRequest.Size(m)
}
func (m *VerificationTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationTokenRequest proto.InternalMessageInfo

func (m *VerificationTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerificationTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VerificationTokenRequest) GetReturnUserInfo() bool {
	if m != nil {
		return m.ReturnUserInfo
	}
	return false
}

// VerificationTokenResponse 验证Token响应参数
type VerificationTokenResponse struct {
	Err *errors.BusinessError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	// 是否允许
	Allow bool `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	// 用户信息
	UserInfo             *VerificationTokenResponse_UserInfo `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *VerificationTokenResponse) Reset()         { *m = VerificationTokenResponse{} }
func (m *VerificationTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationTokenResponse) ProtoMessage()    {}
func (*VerificationTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{3}
}
func (m *VerificationTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationTokenResponse.Unmarshal(m, b)
}
func (m *VerificationTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationTokenResponse.Marshal(b, m, deterministic)
}
func (dst *VerificationTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationTokenResponse.Merge(dst, src)
}
func (m *VerificationTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationTokenResponse.Size(m)
}
func (m *VerificationTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationTokenResponse proto.InternalMessageInfo

func (m *VerificationTokenResponse) GetErr() *errors.BusinessError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *VerificationTokenResponse) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

func (m *VerificationTokenResponse) GetUserInfo() *VerificationTokenResponse_UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// 用户信息
type VerificationTokenResponse_UserInfo struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Gender               uint32   `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationTokenResponse_UserInfo) Reset()         { *m = VerificationTokenResponse_UserInfo{} }
func (m *VerificationTokenResponse_UserInfo) String() string { return proto.CompactTextString(m) }
func (*VerificationTokenResponse_UserInfo) ProtoMessage()    {}
func (*VerificationTokenResponse_UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_b9dcd2af2cd95cd7, []int{3, 0}
}
func (m *VerificationTokenResponse_UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationTokenResponse_UserInfo.Unmarshal(m, b)
}
func (m *VerificationTokenResponse_UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationTokenResponse_UserInfo.Marshal(b, m, deterministic)
}
func (dst *VerificationTokenResponse_UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationTokenResponse_UserInfo.Merge(dst, src)
}
func (m *VerificationTokenResponse_UserInfo) XXX_Size() int {
	return xxx_messageInfo_VerificationTokenResponse_UserInfo.Size(m)
}
func (m *VerificationTokenResponse_UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationTokenResponse_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationTokenResponse_UserInfo proto.InternalMessageInfo

func (m *VerificationTokenResponse_UserInfo) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *VerificationTokenResponse_UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerificationTokenResponse_UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *VerificationTokenResponse_UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *VerificationTokenResponse_UserInfo) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func init() {
	proto.RegisterType((*VerificationHttpRouterRequest)(nil), "nilorg.naas.pkg.proto.VerificationHttpRouterRequest")
	proto.RegisterType((*VerificationHttpRouterResponse)(nil), "nilorg.naas.pkg.proto.VerificationHttpRouterResponse")
	proto.RegisterType((*VerificationHttpRouterResponse_UserInfo)(nil), "nilorg.naas.pkg.proto.VerificationHttpRouterResponse.UserInfo")
	proto.RegisterType((*VerificationTokenRequest)(nil), "nilorg.naas.pkg.proto.VerificationTokenRequest")
	proto.RegisterType((*VerificationTokenResponse)(nil), "nilorg.naas.pkg.proto.VerificationTokenResponse")
	proto.RegisterType((*VerificationTokenResponse_UserInfo)(nil), "nilorg.naas.pkg.proto.VerificationTokenResponse.UserInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PermissionClient interface {
	// VerificationToken 验证Token
	VerificationToken(ctx context.Context, in *VerificationTokenRequest, opts ...grpc.CallOption) (*VerificationTokenResponse, error)
	// VerificationHttpRouter 验证Http路由权限
	VerificationHttpRouter(ctx context.Context, in *VerificationHttpRouterRequest, opts ...grpc.CallOption) (*VerificationHttpRouterResponse, error)
}

type permissionClient struct {
	cc *grpc.ClientConn
}

func NewPermissionClient(cc *grpc.ClientConn) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) VerificationToken(ctx context.Context, in *VerificationTokenRequest, opts ...grpc.CallOption) (*VerificationTokenResponse, error) {
	out := new(VerificationTokenResponse)
	err := c.cc.Invoke(ctx, "/nilorg.naas.pkg.proto.Permission/VerificationToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) VerificationHttpRouter(ctx context.Context, in *VerificationHttpRouterRequest, opts ...grpc.CallOption) (*VerificationHttpRouterResponse, error) {
	out := new(VerificationHttpRouterResponse)
	err := c.cc.Invoke(ctx, "/nilorg.naas.pkg.proto.Permission/VerificationHttpRouter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
type PermissionServer interface {
	// VerificationToken 验证Token
	VerificationToken(context.Context, *VerificationTokenRequest) (*VerificationTokenResponse, error)
	// VerificationHttpRouter 验证Http路由权限
	VerificationHttpRouter(context.Context, *VerificationHttpRouterRequest) (*VerificationHttpRouterResponse, error)
}

func RegisterPermissionServer(s *grpc.Server, srv PermissionServer) {
	s.RegisterService(&_Permission_serviceDesc, srv)
}

func _Permission_VerificationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).VerificationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilorg.naas.pkg.proto.Permission/VerificationToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).VerificationToken(ctx, req.(*VerificationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_VerificationHttpRouter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationHttpRouterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).VerificationHttpRouter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nilorg.naas.pkg.proto.Permission/VerificationHttpRouter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).VerificationHttpRouter(ctx, req.(*VerificationHttpRouterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Permission_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nilorg.naas.pkg.proto.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificationToken",
			Handler:    _Permission_VerificationToken_Handler,
		},
		{
			MethodName: "VerificationHttpRouter",
			Handler:    _Permission_VerificationHttpRouter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/permission.proto",
}

func init() {
	proto.RegisterFile("pkg/proto/permission.proto", fileDescriptor_permission_b9dcd2af2cd95cd7)
}

var fileDescriptor_permission_b9dcd2af2cd95cd7 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xc1, 0x6e, 0x13, 0x3b,
	0x14, 0xd5, 0x24, 0xaf, 0x79, 0x93, 0x8b, 0x40, 0x60, 0x41, 0x19, 0x02, 0xad, 0xa2, 0x01, 0xa4,
	0xb4, 0x48, 0x63, 0x54, 0x40, 0x88, 0x2e, 0x58, 0x54, 0x42, 0x22, 0x1b, 0x84, 0x46, 0xb4, 0x0b,
	0x58, 0x8c, 0x9c, 0xe4, 0x66, 0x62, 0x65, 0x62, 0x0f, 0xb6, 0xa7, 0xdd, 0xf3, 0x0b, 0xfd, 0x02,
	0xf6, 0xac, 0xf9, 0x11, 0x36, 0xac, 0x11, 0x1b, 0xfe, 0x02, 0xd9, 0x9e, 0x94, 0xa0, 0xa6, 0x28,
	0x05, 0xb1, 0x60, 0x95, 0x9c, 0x73, 0xc7, 0xf6, 0xb9, 0xe7, 0xd8, 0x17, 0x3a, 0xe5, 0x34, 0xa7,
	0xa5, 0x92, 0x46, 0xd2, 0x12, 0xd5, 0x8c, 0x6b, 0xcd, 0xa5, 0x48, 0x1c, 0x41, 0xae, 0x09, 0x5e,
	0x48, 0x95, 0x27, 0x82, 0x31, 0x9d, 0x94, 0xd3, 0xdc, 0xd3, 0x9d, 0x5b, 0xb9, 0x94, 0x79, 0x81,
	0x94, 0x95, 0x9c, 0x32, 0x21, 0xa4, 0x61, 0x86, 0x4b, 0xa1, 0xeb, 0xea, 0x3d, 0xbf, 0xc8, 0xef,
	0x39, 0xa8, 0xc6, 0x14, 0x95, 0x92, 0x4a, 0xd3, 0x41, 0xa5, 0xb9, 0x40, 0xad, 0x33, 0x87, 0xfd,
	0xc7, 0xf1, 0x87, 0x00, 0x36, 0x0e, 0x50, 0xf1, 0x31, 0x1f, 0xba, 0x4d, 0x9e, 0x1b, 0x53, 0xa6,
	0xb2, 0x32, 0xa8, 0x52, 0x7c, 0x5b, 0xa1, 0x36, 0xe4, 0x2a, 0xac, 0x19, 0x39, 0x45, 0x11, 0x05,
	0xdd, 0xa0, 0xd7, 0x4e, 0x3d, 0x20, 0x37, 0xa1, 0x3d, 0x2c, 0x38, 0x0a, 0x93, 0xf1, 0x51, 0xd4,
	0x70, 0x95, 0xd0, 0x13, 0xfd, 0x11, 0x59, 0x87, 0x96, 0x72, 0x7b, 0x44, 0x4d, 0x57, 0xa9, 0x91,
	0xe5, 0x67, 0x68, 0x26, 0x72, 0x14, 0xfd, 0xe7, 0x79, 0x8f, 0x48, 0x0f, 0x2e, 0x2b, 0x34, 0x95,
	0x12, 0x59, 0xa5, 0x51, 0x65, 0x5c, 0x8c, 0x65, 0xb4, 0xd6, 0x0d, 0x7a, 0x61, 0x7a, 0xc9, 0xf3,
	0xfb, 0x1a, 0x55, 0x5f, 0x8c, 0x65, 0xfc, 0xa5, 0x01, 0x9b, 0x67, 0xc9, 0xd5, 0xa5, 0x14, 0x1a,
	0xc9, 0x63, 0x68, 0xa2, 0x52, 0x4e, 0xed, 0x85, 0x9d, 0xbb, 0x49, 0xed, 0xe0, 0xdc, 0x8c, 0xc4,
	0x9b, 0x91, 0xec, 0xd5, 0x66, 0x3c, 0xb3, 0x30, 0xb5, 0x2b, 0x6c, 0xa3, 0xac, 0x28, 0xe4, 0x91,
	0x6b, 0x27, 0x4c, 0x3d, 0x20, 0x6f, 0xa0, 0xfd, 0x43, 0x54, 0xd3, 0x6d, 0xfa, 0x34, 0x59, 0x1a,
	0x4b, 0xf2, 0x6b, 0x61, 0xc9, 0xbc, 0x89, 0x34, 0xac, 0xea, 0x7f, 0x9d, 0xe3, 0x00, 0xc2, 0x39,
	0x4d, 0xae, 0xc3, 0xff, 0xb2, 0x44, 0x61, 0x0d, 0xf5, 0x56, 0xb7, 0x2c, 0xec, 0x8f, 0x48, 0x07,
	0xdc, 0x0a, 0xc1, 0x66, 0x38, 0xb7, 0x7a, 0x8e, 0x6d, 0x0e, 0x82, 0x0f, 0xa7, 0x99, 0x2b, 0x7a,
	0xb7, 0x43, 0x4b, 0xbc, 0xb0, 0xc5, 0x0d, 0x00, 0x76, 0xc8, 0x0c, 0x53, 0x59, 0xa5, 0x8a, 0xda,
	0xf3, 0xb6, 0x67, 0xf6, 0x55, 0x61, 0xe3, 0xc8, 0x51, 0x8c, 0x50, 0x39, 0xb3, 0x2f, 0xa6, 0x35,
	0x8a, 0x8f, 0x20, 0x5a, 0x6c, 0xe5, 0x95, 0x0d, 0xfc, 0x0f, 0x6e, 0xc3, 0xea, 0xe9, 0x7e, 0x6e,
	0xc0, 0x8d, 0x25, 0x27, 0xff, 0x9d, 0x60, 0x0f, 0x4e, 0x07, 0xfb, 0x64, 0x85, 0x60, 0x7f, 0xd2,
	0xf4, 0xcf, 0x64, 0xba, 0xf3, 0xad, 0x01, 0xf0, 0xf2, 0x64, 0xbc, 0x90, 0xf7, 0x01, 0x5c, 0x39,
	0xd5, 0x15, 0xa1, 0xab, 0xf7, 0xef, 0x6e, 0x43, 0xe7, 0xfe, 0x79, 0x0d, 0x8b, 0xb7, 0xde, 0x7d,
	0xfa, 0x7a, 0xdc, 0xb8, 0x1d, 0x6f, 0x2e, 0x0c, 0x3b, 0x7a, 0xb8, 0xf0, 0x79, 0xe6, 0x6e, 0xd4,
	0x6e, 0xb0, 0x4d, 0x3e, 0x06, 0xb0, 0xbe, 0xfc, 0x49, 0x91, 0x87, 0xe7, 0x7c, 0x81, 0x5e, 0xed,
	0xa3, 0xdf, 0x7a, 0xb7, 0x31, 0x75, 0x92, 0xb7, 0xe2, 0x3b, 0x67, 0x4a, 0x9e, 0x18, 0x53, 0x66,
	0x7e, 0xc6, 0xed, 0x06, 0xdb, 0x7b, 0xf1, 0xeb, 0x6e, 0xce, 0xcd, 0xa4, 0x1a, 0x24, 0x43, 0x39,
	0xa3, 0xf5, 0x34, 0xb6, 0x67, 0xd2, 0x93, 0x51, 0x3f, 0x68, 0xb9, 0x9f, 0x07, 0xdf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x03, 0xe2, 0xdc, 0x48, 0xfe, 0x05, 0x00, 0x00,
}
